[dev]
  command = "yarn start"
  framework = "#custom"
  publish = "public"
  targetPort = 8080
  port = 9090
  autoLaunch = false

[[redirects]]
  from = "/"
  to = "https://www.example.com"
  status = 301
  force = true